CREATE DATABASE IF NOT EXISTS cheese_project;
USE cheese_project;
CREATE TABLE IF NOT EXISTS words(id INT NOT NULL AUTO_INCREMENT,word VARCHAR(100) NOT NULL,meaning VARCHAR(250),PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS subtitle(id INT NOT NULL AUTO_INCREMENT,percent FLOAT NOT NULL,count_words INT NOT NULL,PRIMARY KEY(id));
